"""Add actuators, tanks, sensors, and weather tables

Revision ID: 398c9913a9db
Revises: 410686c92e70
Create Date: 2026-09-11 12:56:24.547251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398c9913a9db'
down_revision = '410686c92e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('zone', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('auto_threshold', sa.Float(), nullable=True),
    sa.Column('last_toggled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('pump_status', sa.String(length=10), nullable=True),
    sa.Column('auto_mode', sa.Boolean(), nullable=True),
    sa.Column('low_level_threshold', sa.Float(), nullable=True),
    sa.Column('fill_level_threshold', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('forecast', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('tanks')
    op.drop_table('sensors')
    op.drop_table('actuators')
    # ### end Alembic commands ###
