from .auth import auth_bp
from .plots import plots_bp
from .batches import batches_bp
from .care import care_bp
from .harvest import harvest_bp
from .financial import financial_bp
from .pest import pest_bp
from .tasks import tasks_bp
from .actuators import actuators_bp
from .tank import tank_bp
from .sensors import sensors_bp
from .weather import weather_bp
from .alerts import alerts_bp