from .auth import auth_bp
from .plots import plots_bp
from .batches import batches_bp
from .care import care_bp
from .harvest import harvest_bp
from .financial import financial_bp
from .pest import pest_bp
from .tasks import tasks_bp
from .stubs import stubs_bp